# K230686 - DS-Lab-02

In [2]:
import pandas as pd
import numpy as np

# Question 1

## 1a

In [4]:
df1 = pd.read_csv("/content/data1.csv", index_col=0)
df2 = pd.read_csv("/content/data2.csv", index_col=1)
df4 = pd.read_csv("/content/data3.csv", index_col=0)
df6 = pd.read_json("/content/data.json")

display(df1.style.set_caption("DataFrame 1"), df2.style.set_caption("DataFrame 2"), df4.style.set_caption("DataFrame 4"), df6.style.set_caption("DataFrame 6"))


## 1b - Concatenate

In [5]:
df3 = pd.concat( [df1, df2] )
display(df3)

A    B  C
0      1  2.0  3
1      4  5.0  6
4      2  NaN  5
2      2  5.0  6
3  Hello  3.0  4

## 1c - Join

In [7]:
df5 = df3.join(df4)
display(df3, df4, df5)

A    B  C
0      1  2.0  3
1      4  5.0  6
4      2  NaN  5
2      2  5.0  6
3  Hello  3.0  4

D  E
1  1  7
4  0  8

A    B  C    D    E
0      1  2.0  3  NaN  NaN
1      4  5.0  6  1.0  7.0
4      2  NaN  5  0.0  8.0
2      2  5.0  6  NaN  NaN
3  Hello  3.0  4  NaN  NaN

## 1d - IMP

In [8]:
max_idx = df5.index.max()
df6_tmp = df6.copy()

df6_tmp.index = range(max_idx + 1, max_idx + 1 + len(df6))


df7 = pd.concat([df5, df6_tmp], sort=False)
display(df5, df6, df7)

A    B  C    D    E
0      1  2.0  3  NaN  NaN
1      4  5.0  6  1.0  7.0
4      2  NaN  5  0.0  8.0
2      2  5.0  6  NaN  NaN
3  Hello  3.0  4  NaN  NaN

A  B
0  11  9
1  22  7
2  33  8

A    B    C    D    E
0      1  2.0  3.0  NaN  NaN
1      4  5.0  6.0  1.0  7.0
4      2  NaN  5.0  0.0  8.0
2      2  5.0  6.0  NaN  NaN
3  Hello  3.0  4.0  NaN  NaN
5     11  9.0  NaN  NaN  NaN
6     22  7.0  NaN  NaN  NaN
7     33  8.0  NaN  NaN  NaN

## 1e - Value Replacement

In [9]:
df7.replace("Hello", np.nan, inplace=True)
df7

A    B    C    D    E
0    1  2.0  3.0  NaN  NaN
1    4  5.0  6.0  1.0  7.0
4    2  NaN  5.0  0.0  8.0
2    2  5.0  6.0  NaN  NaN
3  NaN  3.0  4.0  NaN  NaN
5   11  9.0  NaN  NaN  NaN
6   22  7.0  NaN  NaN  NaN
7   33  8.0  NaN  NaN  NaN

## 1f - Mean Imputation

In [10]:
df7["A"] = pd.to_numeric(df7['A'], errors='coerce')
df8 = df7.fillna(df7.mean(numeric_only=True))
df8

A         B    C    D    E
0   1.000000  2.000000  3.0  0.5  7.5
1   4.000000  5.000000  6.0  1.0  7.0
4   2.000000  5.571429  5.0  0.0  8.0
2   2.000000  5.000000  6.0  0.5  7.5
3  10.714286  3.000000  4.0  0.5  7.5
5  11.000000  9.000000  4.8  0.5  7.5
6  22.000000  7.000000  4.8  0.5  7.5
7  33.000000  8.000000  4.8  0.5  7.5

In [11]:
df8.to_csv("/content/newdata.csv")

# Question 2 - List Operations

In [20]:
first: list = [11.25, 18.0, 20.0, 10.75, 9.5]
second: list= [10.75, 9.50]

full = first+second
print(f"First: {first}")
print(f"Second: {second}")
print(f"First + Second: {full}")

full_sorted = sorted(full, reverse=True) # slightly more efficient but not inplace unlike list.sort()
print(f"Full Sorted: {full_sorted}")

full_sorted.reverse()
print(f"Reversed Full Sorted: {full_sorted}")

First: [11.25, 18.0, 20.0, 10.75, 9.5]
Second: [10.75, 9.5]
First + Second: [11.25, 18.0, 20.0, 10.75, 9.5, 10.75, 9.5]
Full Sorted: [20.0, 18.0, 11.25, 10.75, 10.75, 9.5, 9.5]
Reversed Full Sorted: [9.5, 9.5, 10.75, 10.75, 11.25, 18.0, 20.0]


In [22]:
from math import pi

radius = int(input("Radius: "))
print(f"Area: {pi*radius**2}")
print(f"Circumference: {2*pi*radius}")

Radius: 1
Area: 3.141592653589793
Circumference: 6.283185307179586


# Question 3 - NP Array Creation

In [29]:
height = np.array( [74, 74, 72, 72, 73, 69, 69, 71, 76, 71, 73, 73, 74, 74, 69, 70, 73, 75, 78, 79, 76, 74, 76, 72, 71, 75,
77, 74, 73, 74, 78, 73, 75, 73] )

weight = np.array( [180, 195, 195, 190, 230, 190, 200, 190, 190, 200, 200, 184, 200, 180, 219, 187, 200, 220, 205, 190, 170, 160, 215, 175, 205, 200, 214, 200,
190, 180, 205, 220, 190, 215] )

# Converting from inches to meters
height = height*0.0254
print(f"Height: {height}")

# Converting from pounds to kilograms
weight = weight*0.453592
print(f"Weight: {weight}")

BMI = weight/height**2
print(f"BMI: {BMI}")

Height: [1.8796 1.8796 1.8288 1.8288 1.8542 1.7526 1.7526 1.8034 1.9304 1.8034
 1.8542 1.8542 1.8796 1.8796 1.7526 1.778  1.8542 1.905  1.9812 2.0066
 1.9304 1.8796 1.9304 1.8288 1.8034 1.905  1.9558 1.8796 1.8542 1.8796
 1.9812 1.8542 1.905  1.8542]
Weight: [ 81.64656   88.45044   88.45044   86.18248  104.32616   86.18248
  90.7184    86.18248   86.18248   90.7184    90.7184    83.460928
  90.7184    81.64656   99.336648  84.821704  90.7184    99.79024
  92.98636   86.18248   77.11064   72.57472   97.52228   79.3786
  92.98636   90.7184    97.068688  90.7184    86.18248   81.64656
  92.98636   99.79024   86.18248   97.52228 ]
BMI: [23.11037639 25.03624109 26.44646146 25.76834706 30.3445058  28.05778432
 29.53450981 26.49932775 23.12726994 27.89402921 26.38652678 24.27560464
 25.67819599 23.11037639 32.34028825 26.83140901 26.38652678 27.49781002
 23.68986625 21.40411972 20.69282047 20.54255679 26.17033177 23.73400387
 28.59137994 24.99800911 25.37641547 25.67819599 25.06720044 23.1103

# Question 3 - NP Descriptive Statistics

In [39]:
mylist = np.array( [[180, 78.4], [215, 102.7], [210, 98.5], [188, 75.2]] )
print(f"Type: {mylist.dtype}")
print(f"Shape: {mylist.shape}")
print(f"2nd Column: {mylist[:,1]}")
print(f"3rd Row and 0th Column: {mylist[2, 0]}")

npheight = mylist[:,0]
print(f"npHeight: {npheight}")
print(f"npHeight Median: {np.median(npheight)}")
print(f"npHeight Mean: {np.mean(npheight)}")
print(f"npHeight STD: {np.std(npheight)}")

Type: float64
Shape: (4, 2)
2nd Column: [ 78.4 102.7  98.5  75.2]
3rd Row and 0th Column: 210.0
npHeight: [180. 215. 210. 188.]
npHeight Median: 199.0
npHeight Mean: 198.25
npHeight STD: 14.635146053251399


# Question 4 - NP Array Slicing/Indexing

In [41]:
# dummy data: 7 days x 24 hours
data = np.arange(7*24).reshape(7, 24)

# every other hour of Day 1
a = data[0,::2]
print("Day1 every other hour:", a)

# first 12 hours for all days
b = data[:,:12]
print("First 12 hours all days:\n", b)

# every 6th hour
c = data[:,::6]
print("Every 6th hour all days:\n", c)

# last 3 days
e = data[4:,:]
print("Last 3 days:\n", e)

# reverse Day 3
f = data[2,::-1]
print("Day 3 reversed:", f)

# every 3rd hour, first 4 days
g = data[:4,::3]
print("Every 3rd hour first 4 days:\n", g)


Day1 every other hour: [ 0  2  4  6  8 10 12 14 16 18 20 22]
First 12 hours all days:
 [[  0   1   2   3   4   5   6   7   8   9  10  11]
 [ 24  25  26  27  28  29  30  31  32  33  34  35]
 [ 48  49  50  51  52  53  54  55  56  57  58  59]
 [ 72  73  74  75  76  77  78  79  80  81  82  83]
 [ 96  97  98  99 100 101 102 103 104 105 106 107]
 [120 121 122 123 124 125 126 127 128 129 130 131]
 [144 145 146 147 148 149 150 151 152 153 154 155]]
Every 6th hour all days:
 [[  0   6  12  18]
 [ 24  30  36  42]
 [ 48  54  60  66]
 [ 72  78  84  90]
 [ 96 102 108 114]
 [120 126 132 138]
 [144 150 156 162]]
Last 3 days:
 [[ 96  97  98  99 100 101 102 103 104 105 106 107 108 109 110 111 112 113
  114 115 116 117 118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139 140 141 142 143]
 [144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
  162 163 164 165 166 167]]
Day 3 reversed: [71 70 69 68 67 66 65 64 63 62 61 60 59 58 57 56 55 54 53 52 